//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromZoomDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos_Tab
    {
        public Nullable<long> DB_ { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<long> Facility_ID { get; set; }
        public string Fac_NAME { get; set; }
        public string Fac_Address_1 { get; set; }
        public string Fac_Address_2 { get; set; }
        public string Fac_City { get; set; }
        public string Fac_State { get; set; }
        public string Fac_Zip { get; set; }
        public string Fac_PHONE { get; set; }
        public string Fac_FAX { get; set; }
        public string Fac_Email { get; set; }
        public string Billing_Address1 { get; set; }
        public string Billing_Address2 { get; set; }
        public string Billing_City { get; set; }
        public string Billing_State { get; set; }
        public string Billing_Zip { get; set; }
        public string Billing_Phone { get; set; }
        public string Billing_Fax { get; set; }
        public string Billing_Email { get; set; }
        public Nullable<long> Federal_Tax_ID { get; set; }
        public string CLIA_ID { get; set; }
        public string POS { get; set; }
        public Nullable<long> NPI { get; set; }
        public string CheckPayableTo { get; set; }
        public string MamographyCertificationNo { get; set; }
        public string FacilityCode { get; set; }
        public string Facility_Type { get; set; }
        public int I_Pos_Tab { get; set; }
    }
}
