//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionCode
    {
        public int ActionCodeID { get; set; }
        public string CollNoteType { get; set; }
        public int CodeID { get; set; }
        public int CategoryID { get; set; }
        public int PriorityID { get; set; }
        public int ACTypeID { get; set; }
        public bool Active { get; set; }
        public string ParsingYN { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ACCategory ACCategory { get; set; }
        public virtual ACPriority ACPriority { get; set; }
        public virtual ACtype ACtype { get; set; }
        public virtual CodeMasterList CodeMasterList { get; set; }
    }
}
