//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogID { get; set; }
        public string TableName { get; set; }
        public string UserLogons { get; set; }
        public System.DateTime AuditDateTime { get; set; }
        public string Field_ColumName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string AuditAction { get; set; }
        public int ModelPKey { get; set; }
    }
}
