//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollNoteTypeCatPriority
    {
        public int id { get; set; }
        public string CollNoteType { get; set; }
        public string Code { get; set; }
        public string CollNoteCat { get; set; }
        public string Priority { get; set; }
        public string NTUser { get; set; }
        public bool Active { get; set; }
        public string ParsingYN { get; set; }
        public string ACType { get; set; }
    }
}
