//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corp_DBs
    {
        public int ID_PK { get; set; }
        public int corpID { get; set; }
        public int DB_ID { get; set; }
    
        public virtual CorporateMasterList CorporateMasterList { get; set; }
        public virtual DBList DBList { get; set; }
    }
}
