//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edgemed_Logons
    {
        public int Edgemed_LogID { get; set; }
        public int ADPMasterID { get; set; }
        public string Edgemed_UserName { get; set; }
        public int Zno { get; set; }
        public int EdgeMed_ID { get; set; }
        public bool Active { get; set; }
    
        public virtual ADPMaster ADPMaster { get; set; }
    }
}
