//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms_sent
    {
        public int FormSentID { get; set; }
        public int FormsDict_FormsID { get; set; }
        public int MasterPOS_MasterPOSID { get; set; }
    
        public virtual FormsDict FormsDict { get; set; }
        public virtual MasterPOS MasterPOS { get; set; }
    }
}
