//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoData()
        {
            this.MasterPOS = new HashSet<MasterPOS>();
        }
    
        public int InfoDataID { get; set; }
        public string LicType { get; set; }
        public string StateLic { get; set; }
        public string LicNumCLIA_waiver { get; set; }
        public System.DateTime LicEffectiveDate { get; set; }
        public System.DateTime LicExpireDate { get; set; }
        public string Taxonomy { get; set; }
        public Nullable<System.DateTime> CLIA_EffectiveDate { get; set; }
        public Nullable<System.DateTime> CLIA_ExpireDate { get; set; }
        public string LicNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterPOS> MasterPOS { get; set; }
    }
}
