//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationsPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationsPOS()
        {
            this.LocPOS_LevOfCare = new HashSet<LocPOS_LevOfCare>();
            this.LocPOS_MPServ = new HashSet<LocPOS_MPServ>();
        }
    
        public int Facitity_DBs_IDPK { get; set; }
        public string PosName { get; set; }
        public int FvPList_FvPID { get; set; }
        public Nullable<int> FACInfoData_FACInfoDataID { get; set; }
        public string TaxID { get; set; }
        public string DBA_Name { get; set; }
        public string Payment_Addr1 { get; set; }
        public string Payment_Addr2 { get; set; }
        public string Payment_City { get; set; }
        public string Payment_state { get; set; }
        public string Payment_Zip { get; set; }
        public string Physical_Addr1 { get; set; }
        public string Physical_Addr2 { get; set; }
        public string Physical_City { get; set; }
        public string Physical_state { get; set; }
        public string Physical_Zip { get; set; }
        public string POSFAC_Manager { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PHYGroups_PHYGrpID { get; set; }
        public string Time_Zone { get; set; }
    
        public virtual Facitity_DBs Facitity_DBs { get; set; }
        public virtual FvPList FvPList { get; set; }
        public virtual PHYGroup PHYGroup { get; set; }
        public virtual FACInfoData FACInfoData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocPOS_LevOfCare> LocPOS_LevOfCare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocPOS_MPServ> LocPOS_MPServ { get; set; }
    }
}
