//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocPOS_MPServ
    {
        public int LocPosMPServID { get; set; }
        public int MPServices_MPServID { get; set; }
        public Nullable<int> LocationsPOS_Facitity_DBs_IDPK { get; set; }
    
        public virtual MPService MPService { get; set; }
        public virtual LocationsPOS LocationsPOS { get; set; }
    }
}
