//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocPOS_LevOfCare
    {
        public int LocPosLocID { get; set; }
        public int Lev_of_Care_LevOfCareID { get; set; }
        public Nullable<int> LocationsPOS_Facitity_DBs_IDPK { get; set; }
    
        public virtual Lev_of_Care Lev_of_Care { get; set; }
        public virtual LocationsPOS LocationsPOS { get; set; }
    }
}
