//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocPOS_Contact
    {
        public int Facility_DBs_IDPK { get; set; }
        public int ContactID { get; set; }
        public int LocPOSContactID { get; set; }
    
        public virtual LocationsPOS LocationsPOS { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
