//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerDBAccessBI
    {
        public int id { get; set; }
        public string FvP { get; set; }
        public string DB { get; set; }
        public string Manager { get; set; }
        public string AliasName { get; set; }
        public string NTUser { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
