//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterPOS()
        {
            this.MasterPOS_LevOfCare = new HashSet<MasterPOS_LevOfCare>();
            this.MasterPOS_MPServ = new HashSet<MasterPOS_MPServ>();
            this.Forms_sent = new HashSet<Forms_sent>();
            this.MasterPOS_Contact = new HashSet<MasterPOS_Contact>();
            this.ZoomDB_POSID_grp = new HashSet<ZoomDB_POSID_grp>();
            this.MasterFiles = new HashSet<MasterFile>();
        }
    
        public int MasterPOSID { get; set; }
        public string PosMasterName { get; set; }
        public bool active { get; set; }
        public int FvPList_FvPID { get; set; }
        public Nullable<int> InfoData_InfoDataID { get; set; }
        public Nullable<int> POSExtraData_POSExtraDataID { get; set; }
        public Nullable<int> POSAddr_POSAddrID { get; set; }
        public Nullable<int> PHYGroups_PHYGrpID { get; set; }
        public int Manager_Master_ManagerID { get; set; }
        public int Providers_ProvID { get; set; }
        public Nullable<int> FACInfo_FACInfoID { get; set; }
        public int DBList_DB_ID { get; set; }
    
        public virtual DBList DBList { get; set; }
        public virtual FvPList FvPList { get; set; }
        public virtual Manager_Master Manager_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterPOS_LevOfCare> MasterPOS_LevOfCare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterPOS_MPServ> MasterPOS_MPServ { get; set; }
        public virtual POSAddr POSAddr { get; set; }
        public virtual FACInfo FACInfo { get; set; }
        public virtual PHYGroup PHYGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forms_sent> Forms_sent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterPOS_Contact> MasterPOS_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoomDB_POSID_grp> ZoomDB_POSID_grp { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual InfoData InfoData { get; set; }
        public virtual POSExtraData POSExtraData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterFile> MasterFiles { get; set; }
    }
}
