//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterUserList
    {
        public int id { get; set; }
        public string ADP_ID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<long> ADP_ID_ { get; set; }
        public string Edgemed_UserName { get; set; }
        public Nullable<long> ZoomServer { get; set; }
        public Nullable<long> EdgeMed_ID { get; set; }
        public string Job_Title { get; set; }
        public string Staff_Manager { get; set; }
        public string User_Active { get; set; }
        public string FirstName { get; set; }
        public string Middle_Init { get; set; }
        public string LastName { get; set; }
        public string NTUser { get; set; }
        public string Type { get; set; }
    }
}
