//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterFile
    {
        public int FileID { get; set; }
        public string ServerLocation { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string Description { get; set; }
        public System.DateTime UploadTime { get; set; }
        public int FileTypeID { get; set; }
        public int MasterPOS_MasterPOSID { get; set; }
        public bool Active { get; set; }
        public string UserLogons { get; set; }
    
        public virtual FileTypeI FileTypeI { get; set; }
        public virtual MasterPOS MasterPOS { get; set; }
    }
}
