//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDM_POS_ListName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDM_POS_ListName()
        {
            this.MDM_POS_Name_DBPOS_grp = new HashSet<MDM_POS_Name_DBPOS_grp>();
        }
    
        public int MDMPOS_ListNameID { get; set; }
        public string PosName { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDM_POS_Name_DBPOS_grp> MDM_POS_Name_DBPOS_grp { get; set; }
    }
}
