//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDM_POS_Name_DBPOS_grp
    {
        //PK
        public int MDMPOS_NameID { get; set; }

        //FK from dbo.DBList
        public int DB_ID { get; set; }

        //FK from dbo.Facility_Dbs
        public long FacilityID { get; set; }

        public string Extra { get; set; }

        //FK from dbo.MDM_POS_ListName
        public int MDMPOS_ListNameID { get; set; }
        public bool Active { get; set; }
    
        public virtual MDM_POS_ListName MDM_POS_ListName { get; set; }
    }
}
