//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSAddr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POSAddr()
        {
            this.MasterPOS = new HashSet<MasterPOS>();
        }
    
        public int POSAddrID { get; set; }
        public string DBA_Name { get; set; }
        public string Payment_Addr1 { get; set; }
        public string Payment_Addr2 { get; set; }
        public string Payment_City { get; set; }
        public string Payment_state { get; set; }
        public string Payment_Zip { get; set; }
        public string Physical_Addr1 { get; set; }
        public string Physical_Addr2 { get; set; }
        public string Physical_City { get; set; }
        public string Physical_state { get; set; }
        public string Physical_Zip { get; set; }
        public string Notes { get; set; }
        public string Time_Zone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterPOS> MasterPOS { get; set; }
    }
}
