//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSLOCExtraData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POSLOCExtraData()
        {
            this.Forms_sent = new HashSet<Forms_sent>();
        }
    
        public int FACInfoData_FACInfoDataID { get; set; }
        public string Phone_Number { get; set; }
        public string Fax_Number { get; set; }
        public string Website { get; set; }
        public Nullable<bool> W_9_on_File { get; set; }
        public string Number_of_beds { get; set; }
        public Nullable<bool> Have_24hrs_nursing { get; set; }
        public string how_many_days_week_open { get; set; }
        public string Ancillary_outpatient_services { get; set; }
        public string Lab_Name { get; set; }
        public string Out_of_Network_In_Network { get; set; }
        public Nullable<bool> Licensure_on_File { get; set; }
        public Nullable<bool> Mental_License { get; set; }
        public string BCBS_ID_Number { get; set; }
        public string UPIN_Number { get; set; }
        public string Medicaid_Number { get; set; }
        public string State_of_MD_or_PhyGrp { get; set; }
        public Nullable<bool> Regulations_on_File { get; set; }
        public string JACHO_CARF { get; set; }
        public Nullable<bool> Has_facility_billed_ins_before { get; set; }
        public string Manage_care_contracts { get; set; }
        public Nullable<bool> Copies_of_all_managed_care_contracts_on_file { get; set; }
        public Nullable<bool> Forms_created { get; set; }
        public Nullable<bool> In_Service_scheduled { get; set; }
        public Nullable<System.DateTime> In_Service_date_time { get; set; }
        public Nullable<bool> Portal_training_setup { get; set; }
        public Nullable<bool> email_regarding_conference_set_up { get; set; }
        public Nullable<bool> Database_set_up { get; set; }
        public Nullable<bool> Availavility_request_sent_out { get; set; }
        public Nullable<bool> Availavility_completed { get; set; }
        public Nullable<bool> Navinet_request_completed { get; set; }
        public Nullable<bool> Fee_schedule_in_binder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forms_sent> Forms_sent { get; set; }
        public virtual FACInfoData FACInfoData { get; set; }
    }
}
