//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidersInGrp
    {
        public int ProvInGrpID { get; set; }
        public int Providers_ProvID { get; set; }
        public int PHYGroups_PHYGrpID { get; set; }
    
        public virtual PHYGroup PHYGroup { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
