//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.WebPortal.Models.FromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoomDB_POSID_grp
    {
        public int ZoomDBPOSID { get; set; }
        public long ZoomPos_ID { get; set; }
        public string Extra { get; set; }
        public int MasterPOSID { get; set; }
        public bool Active { get; set; }
    
        public virtual MasterPOS MasterPOS { get; set; }
    }
}
